<?php

namespace ContainerMCA6MVa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_UZGPtZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uZG_PtZ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uZG_PtZ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'robot' => ['privates', '.errored..service_locator.uZG_PtZ.App\\Entity\\Robot', NULL, 'Cannot autowire service ".service_locator.uZG_PtZ": it needs an instance of "App\\Entity\\Robot" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'robot' => 'App\\Entity\\Robot',
        ]);
    }
}
