<?php

namespace ContainerMCA6MVa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_K_JZ3ASService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.K.JZ3AS' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.K.JZ3AS'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'alert' => ['privates', '.errored..service_locator.K.JZ3AS.App\\Entity\\Alert', NULL, 'Cannot autowire service ".service_locator.K.JZ3AS": it needs an instance of "App\\Entity\\Alert" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'alert' => 'App\\Entity\\Alert',
        ]);
    }
}
