<?php

namespace ContainerMCA6MVa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_PjOA3iDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.pjOA3iD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\Api\\AlertController::acknowledge' => ['privates', '.service_locator.K.JZ3AS.App\\Controller\\Api\\AlertController::acknowledge()', 'getAlertControlleracknowledgeService', true],
            'App\\Controller\\Api\\AlertController::resolve' => ['privates', '.service_locator.K.JZ3AS.App\\Controller\\Api\\AlertController::resolve()', 'getAlertControllerresolveService', true],
            'App\\Controller\\Api\\MaintenanceController::update' => ['privates', '.service_locator.fySquMd.App\\Controller\\Api\\MaintenanceController::update()', 'getMaintenanceControllerupdateService', true],
            'App\\Controller\\Api\\RobotController::show' => ['privates', '.service_locator.uZG_PtZ.App\\Controller\\Api\\RobotController::show()', 'getRobotControllershowService', true],
            'App\\Controller\\Api\\RobotController::status' => ['privates', '.service_locator.uZG_PtZ.App\\Controller\\Api\\RobotController::status()', 'getRobotControllerstatusService', true],
            'App\\Controller\\Api\\RobotController::telemetry' => ['privates', '.service_locator.uZG_PtZ.App\\Controller\\Api\\RobotController::telemetry()', 'getRobotControllertelemetryService', true],
            'App\\Controller\\Api\\RobotController::timeline' => ['privates', '.service_locator.uZG_PtZ.App\\Controller\\Api\\RobotController::timeline()', 'getRobotControllertimelineService', true],
            'App\\Controller\\Api\\SimulationController::tick' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\Api\\SimulationController::tick()', 'getSimulationControllertickService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\Api\\AlertController:acknowledge' => ['privates', '.service_locator.K.JZ3AS.App\\Controller\\Api\\AlertController::acknowledge()', 'getAlertControlleracknowledgeService', true],
            'App\\Controller\\Api\\AlertController:resolve' => ['privates', '.service_locator.K.JZ3AS.App\\Controller\\Api\\AlertController::resolve()', 'getAlertControllerresolveService', true],
            'App\\Controller\\Api\\MaintenanceController:update' => ['privates', '.service_locator.fySquMd.App\\Controller\\Api\\MaintenanceController::update()', 'getMaintenanceControllerupdateService', true],
            'App\\Controller\\Api\\RobotController:show' => ['privates', '.service_locator.uZG_PtZ.App\\Controller\\Api\\RobotController::show()', 'getRobotControllershowService', true],
            'App\\Controller\\Api\\RobotController:status' => ['privates', '.service_locator.uZG_PtZ.App\\Controller\\Api\\RobotController::status()', 'getRobotControllerstatusService', true],
            'App\\Controller\\Api\\RobotController:telemetry' => ['privates', '.service_locator.uZG_PtZ.App\\Controller\\Api\\RobotController::telemetry()', 'getRobotControllertelemetryService', true],
            'App\\Controller\\Api\\RobotController:timeline' => ['privates', '.service_locator.uZG_PtZ.App\\Controller\\Api\\RobotController::timeline()', 'getRobotControllertimelineService', true],
            'App\\Controller\\Api\\SimulationController:tick' => ['privates', '.service_locator.z0A7H.F.App\\Controller\\Api\\SimulationController::tick()', 'getSimulationControllertickService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Api\\AlertController::acknowledge' => '?',
            'App\\Controller\\Api\\AlertController::resolve' => '?',
            'App\\Controller\\Api\\MaintenanceController::update' => '?',
            'App\\Controller\\Api\\RobotController::show' => '?',
            'App\\Controller\\Api\\RobotController::status' => '?',
            'App\\Controller\\Api\\RobotController::telemetry' => '?',
            'App\\Controller\\Api\\RobotController::timeline' => '?',
            'App\\Controller\\Api\\SimulationController::tick' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Api\\AlertController:acknowledge' => '?',
            'App\\Controller\\Api\\AlertController:resolve' => '?',
            'App\\Controller\\Api\\MaintenanceController:update' => '?',
            'App\\Controller\\Api\\RobotController:show' => '?',
            'App\\Controller\\Api\\RobotController:status' => '?',
            'App\\Controller\\Api\\RobotController:telemetry' => '?',
            'App\\Controller\\Api\\RobotController:timeline' => '?',
            'App\\Controller\\Api\\SimulationController:tick' => '?',
        ]);

        if (isset($container->privates['.service_locator.pjOA3iD'])) {
            return $container->privates['.service_locator.pjOA3iD'];
        }

        return $container->privates['.service_locator.pjOA3iD'] = $instance;
    }
}
