<?php

namespace ContainerMCA6MVa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getHealthControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\HealthController' shared autowired service.
     *
     * @return \App\Controller\Api\HealthController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/HealthController.php';

        return $container->services['App\\Controller\\Api\\HealthController'] = new \App\Controller\Api\HealthController();
    }
}
