<?php

namespace ContainerMCA6MVa;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMaintenanceControllerupdateService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fySquMd.App\Controller\Api\MaintenanceController::update()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.fySquMd.App\\Controller\\Api\\MaintenanceController::update()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'ticket' => ['privates', '.errored..service_locator.fySquMd.App\\Entity\\MaintenanceTicket', NULL, 'Cannot autowire service ".service_locator.fySquMd": it needs an instance of "App\\Entity\\MaintenanceTicket" but this type has been excluded because it\'s a Doctrine entity.'],
        ], [
            'ticket' => 'App\\Entity\\MaintenanceTicket',
        ]))->withContext('App\\Controller\\Api\\MaintenanceController::update()', $container);
    }
}
