<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNFEc1xw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNFEc1xw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNFEc1xw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNFEc1xw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNFEc1xw\App_KernelDevDebugContainer([
    'container.build_hash' => 'NFEc1xw',
    'container.build_id' => '80381e43',
    'container.build_time' => 1783764793,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNFEc1xw');
