<?php

namespace ContainerNFEc1xw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlertControlleracknowledgeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.K.JZ3AS.App\Controller\Api\AlertController::acknowledge()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.K.JZ3AS.App\\Controller\\Api\\AlertController::acknowledge()'] = ($container->privates['.service_locator.K.JZ3AS'] ?? $container->load('get_ServiceLocator_K_JZ3ASService'))->withContext('App\\Controller\\Api\\AlertController::acknowledge()', $container);
    }
}
