<?php

namespace ContainerNFEc1xw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAlertService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.K.JZ3AS.App\Entity\Alert' shared service.
     *
     * @return \App\Entity\Alert
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.K.JZ3AS": it needs an instance of "App\\Entity\\Alert" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
