<?php

namespace ContainerNFEc1xw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRobotService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.uZG_PtZ.App\Entity\Robot' shared service.
     *
     * @return \App\Entity\Robot
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.uZG_PtZ": it needs an instance of "App\\Entity\\Robot" but this type has been excluded because it\'s a Doctrine entity.');
    }
}
