<?php

namespace ContainerNFEc1xw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRobotControllerstatusService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.uZG_PtZ.App\Controller\Api\RobotController::status()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.uZG_PtZ.App\\Controller\\Api\\RobotController::status()'] = ($container->privates['.service_locator.uZG_PtZ'] ?? $container->load('get_ServiceLocator_UZGPtZService'))->withContext('App\\Controller\\Api\\RobotController::status()', $container);
    }
}
