<?php

namespace ContainerNFEc1xw;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTestControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Api\TestController' shared autowired service.
     *
     * @return \App\Controller\Api\TestController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/Controller/Api/TestController.php';

        return $container->services['App\\Controller\\Api\\TestController'] = new \App\Controller\Api\TestController();
    }
}
